// lib/defaults.js — Default seed data (backend only, never shipped to client)

const DEFAULT_ALLSTAR = {
  'Dohziez':    { apps:3, wins:3, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Chef_7s':    { apps:3, wins:3, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Aether':     { apps:2, wins:2, mvps:0, dunk:0, skills:0, threepoint:1 },
  'Chris':      { apps:2, wins:2, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Partum':     { apps:2, wins:2, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Cam':        { apps:2, wins:2, mvps:0, dunk:0, skills:0, threepoint:1 },
  'Logs':       { apps:2, wins:2, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Tsutsumi':   { apps:2, wins:2, mvps:1, dunk:0, skills:0, threepoint:0 },
  'Mari':       { apps:2, wins:2, mvps:1, dunk:1, skills:0, threepoint:0 },
  'Pox':        { apps:2, wins:2, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Altf410':    { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Minis':      { apps:1, wins:1, mvps:0, dunk:1, skills:0, threepoint:0 },
  'Cartier':    { apps:1, wins:1, mvps:1, dunk:0, skills:1, threepoint:0 },
  'K_ai6':      { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Tax':        { apps:1, wins:1, mvps:0, dunk:0, skills:2, threepoint:0 },
  'Eazy':       { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Ire':        { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Roji':       { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:2 },
  'Chxf':       { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Steezo':     { apps:1, wins:1, mvps:1, dunk:0, skills:0, threepoint:0 },
  'Combat':     { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Love':       { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Cahmmie':    { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:1 },
  'Loq':        { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Jax':        { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Shawn':      { apps:1, wins:1, mvps:0, dunk:0, skills:1, threepoint:1 },
  'Ben':        { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Javon':      { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Oil':        { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Tom':        { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Trigg':      { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'ZPud':       { apps:1, wins:1, mvps:0, dunk:0, skills:0, threepoint:0 },
  'Llval':      { apps:0, wins:0, mvps:0, dunk:2, skills:0, threepoint:0 },
  'Acro':       { apps:0, wins:0, mvps:0, dunk:0, skills:1, threepoint:0 },
  'Cal':        { apps:0, wins:0, mvps:0, dunk:0, skills:1, threepoint:0 },
  'Bones':      { apps:0, wins:0, mvps:0, dunk:0, skills:1, threepoint:0 },
  'MaybeLaMelo':{ apps:0, wins:0, mvps:0, dunk:0, skills:0, threepoint:3 },
};

const DEFAULT_RECORDS = {
  pts: { label:'Points',     value:169, holder:'Cahmmie',            team:'Spurs' },
  ast: { label:'Assists',    value:64,  holder:'24kslxckz & Tom',    team:'Rockets' },
  reb: { label:'Rebounds',   value:54,  holder:'24kslxckz',          team:'Rockets' },
  stl: { label:'Steals',     value:29,  holder:'24kslxckz',          team:'Celtics' },
  blk: { label:'Blocks',     value:22,  holder:'24kslxckz',          team:'Rockets' },
  tov: { label:'Turnovers',  value:40,  holder:'trey',               team:'Trailblazers' },
};

const DEFAULT_SEASONS = [
  {
    id:1, champion:'Denver Nuggets', record:'7-0',
    defeated:'Boston Celtics', defeatedRecord:'6-2', seriesResult:'2-1 (3 Games)',
    owners:['Minis','ZPud','Northside','Chef_7s','Solarstix'],
    toty:'Boston Celtics', fmvp:'ZPud',
    awards:{ MVP:'Tsutsumi', OPOTY:'Chris', DPOY:'Mari', ROTY:'Omx', MIP:'Zion',
             BMOTY:'Ben', PMOTY:'Javon', CPOTY:'Chef_7s', '4MOTY':'Bomber' },
    allRPL:{
      first:[ {pos:'PG',name:'Mari'},{pos:'SG',name:'Omx'},{pos:'SF',name:'Chris'},{pos:'PF',name:'Tsutsumi'},{pos:'C',name:'Ben'} ],
      second:[ {pos:'PG',name:'Javon'},{pos:'SG',name:'Cal'},{pos:'SF',name:'Zion'},{pos:'PF',name:'Cartier'},{pos:'C',name:'ZPud'} ],
      third:[ {pos:'PG',name:'Bosh'},{pos:'SG',name:'Bomber'},{pos:'SF',name:'Bones'},{pos:'PF',name:'Minis'},{pos:'C',name:'Carson'} ],
    },
  },
  {
    id:2, champion:'Chicago Bulls', record:'8-1',
    defeated:'Golden State Warriors', defeatedRecord:'17-1', seriesResult:'2-0 (2 Games)',
    owners:['Minis','ZPud','Northside','Chef_7s','Solarstix','Zulifix'],
    toty:'Chicago Bulls', fmvp:'ZPud',
    awards:{ MVP:'Tsutsumi', OPOTY:'ZPud', DPOY:'Mari', PMOTY:'Erro', ROTY:'Fearsvamp',
             MIP:'24kslxckz', CPOTY:'Tsutsumi', '4MOTY':'Chef_7s', DEVOTY:'24kslxckz' },
    allRPL:{
      first:[ {pos:'PG',name:'Cal'},{pos:'SG',name:'Tsutsumi'},{pos:'SF',name:'Javon'},{pos:'PF',name:'ZPud'},{pos:'C',name:'Fearsvamp'} ],
      second:[ {pos:'PG',name:'Mari'},{pos:'SG',name:'Slack'},{pos:'SF',name:'Omx'},{pos:'PF',name:'Dohziez'},{pos:'C',name:'Chip'} ],
    },
  },
  {
    id:3, champion:'Golden State Warriors', record:'3-2',
    defeated:'Toronto Raptors', defeatedRecord:'3-1', seriesResult:'2-0 (2 Games)',
    owners:['Dohziez','Counted','Slapclosed','picking_expertise','Mack','Kvqry'],
    toty:'Cleveland Cavaliers', fmvp:'Counted',
    awards:{ MVP:'Tsutsumi', OPOTY:'Cahmmie', DPOY:'Mari', PMOTY:'Yair', ROTY:'Mack',
             MIP:'Erro', '4MOTY':'Slack' },
    statLeaders:{ 'Scoring Champion':'Tsutsumi','Steals Leader':'Durkio','Assist Leader':'Yair','Rebounds Leader':'Yair','Player Efficiency Rating':'Tsutsumi','Turnover Leader':'Mari' },
    allRPL:{
      first:[ {pos:'—',name:'Tsutsumi'},{pos:'—',name:'Cahmmie'},{pos:'—',name:'Chris'},{pos:'—',name:'Tom'},{pos:'—',name:'Counted'} ],
      second:[ {pos:'—',name:'Erro'},{pos:'—',name:'Durkio'},{pos:'—',name:'Cal'},{pos:'—',name:'Mari'},{pos:'—',name:'Chip'} ],
      defensive:[ {pos:'—',name:'Durkio'},{pos:'—',name:'Mari'},{pos:'—',name:'Tom'},{pos:'—',name:'Pelon'},{pos:'—',name:'Chris'} ],
    },
  },
  {
    id:4, champion:'San Antonio Spurs', record:'13-2',
    defeated:'Charlotte Hornets', defeatedRecord:'5-4', seriesResult:'2-0 (2 Games)',
    owners:['Cartier','Mari','Tsutsumi','Roji','Tax','Cam'],
    toty:'San Antonio Spurs', fmvp:'Tsutsumi',
    awards:{ MVP:'Mari', OPOTY:'Javon', DPOY:'Mari', PMOTY:'Kevv', ROTY:'Dom',
             CPOTY:'Chef_7s', MIP:'Curryxiz', '4MOTY':'Cam' },
    statLeaders:{ 'Scoring Champion':'Dom','Steals Leader':'Mari','Assist Leader':'Kevv','Rebounds Leader':'Yair','Player Efficiency Rating':'Dom','Turnover Leader':'Erro' },
    allRPL:{
      first:[ {pos:'PG',name:'Mari'},{pos:'SG',name:'Javon'},{pos:'SF',name:'Tom'},{pos:'PF',name:'Shawn'},{pos:'C',name:'Cartier'} ],
      second:[ {pos:'PG',name:'Logs'},{pos:'SG',name:'Dom'},{pos:'SF',name:'Cal'},{pos:'PF',name:'Ayemoney'},{pos:'C',name:'Master'} ],
      third:[ {pos:'PG',name:'Combat'},{pos:'SG',name:'Chris'},{pos:'SF',name:'Gray'},{pos:'PF',name:'Ire'},{pos:'C',name:'Ben'} ],
      defensive:[ {pos:'PG',name:'Mari'},{pos:'SG',name:'Tom'},{pos:'SF',name:'Durkio'},{pos:'PF',name:'Master'},{pos:'C',name:'Cartier'} ],
    },
  },
  {
    id:5, champion:'Los Angeles Lakers', record:'17-1',
    defeated:'Atlanta Hawks', defeatedRecord:'5-2', seriesResult:'2-0 (2 Games)',
    owners:['Shawn','Cal','Logs','Trigg'],
    toty:'Los Angeles Lakers', fmvp:'Shawn',
    awards:{ MVP:'Shawn', OPOTY:'Dom', DPOY:'Cal', PMOTY:'Kevv', ROTY:'Yurr',
             CPOTY:'Logs', MIP:'lfwq', '4MOTY':'jacce99' },
    statLeaders:{ 'Scoring Champion':'Dom','Steals Leader':'Durkio','Assist Leader':'Kevv','Rebounds Leader':'Roji','Player Efficiency Rating':'Dom','Turnover Leader':'Erro' },
    allRPL:{
      first:[ {pos:'PG',name:'Shawn'},{pos:'SG',name:'Tsutsumi'},{pos:'SF',name:'Dom'},{pos:'PF',name:'Cal'},{pos:'C',name:'Durkio'} ],
      second:[ {pos:'PG',name:'Erro'},{pos:'SG',name:'Logs'},{pos:'SF',name:'lfwq'},{pos:'PF',name:'Pelon'},{pos:'C',name:'jacce99'} ],
      third:[ {pos:'PG',name:'tysoneatsbruh'},{pos:'SG',name:'Roji'},{pos:'SF',name:'Trigg'},{pos:'PF',name:'Ire'},{pos:'C',name:'Ben'} ],
      defensive:[ {pos:'PG',name:'tysoneatsbruh'},{pos:'SG',name:'Kevv'},{pos:'SF',name:'Cal'},{pos:'PF',name:'Pelon'},{pos:'C',name:'Durkio'} ],
    },
  },
  {
    id:6, champion:'Los Angeles Lakers', record:'21-8',
    defeated:'Boston Celtics', defeatedRecord:'15-0', seriesResult:'2-0 (2 Games)',
    owners:['Tom','ZPud','Tsutsumi','Cahmmie','Pekka','Minis'],
    toty:'Boston Celtics', fmvp:'ZPud',
    awards:{ MVP:'Shawn', OPOTY:'Tax', DPOY:'Cal', PMOTY:'Logs', ROTY:'Pekka',
             CPOTY:'Combat', MIP:'Slack', '4MOTY':'Dohziez' },
    allRPL:{
      first:[ {pos:'PG',name:'Tom'},{pos:'SG',name:'Tsutsumi'},{pos:'SF',name:'Cal'},{pos:'PF',name:'Shawn'},{pos:'C',name:'Logs'} ],
      second:[ {pos:'PG',name:'Javon'},{pos:'SG',name:'Tax'},{pos:'SF',name:'Tom'},{pos:'PF',name:'Minis'},{pos:'C',name:'Ire'} ],
      third:[ {pos:'PG',name:'Chris'},{pos:'SG',name:'Cartier'},{pos:'SF',name:'Bones'},{pos:'PF',name:'Jax'},{pos:'C',name:'Chef_7s'} ],
      defensive:[ {pos:'PG',name:'Tom'},{pos:'SG',name:'Cartier'},{pos:'SF',name:'Cal'},{pos:'PF',name:'Master'},{pos:'C',name:'Ire'} ],
    },
  },
  {
    id:7, champion:'Charlotte Hornets', record:'14-9',
    defeated:'Dallas Mavericks', defeatedRecord:'12-3', seriesResult:'2-1 (3 Games)',
    owners:['Shawn','Cal','Tsutsumi','Trigg','Jax','Cam'],
    toty:'Charlotte Hornets', fmvp:'Shawn',
    awards:{ MVP:'Shawn', OPOTY:'Cahmmie', DPOY:'Cartier', PMOTY:'Partum', ROTY:'Odipapedoit',
             CPOTY:'Chris', MIP:'Cam', '4MOTY':'Jax' },
    allRPL:{
      first:[ {pos:'PG',name:'Shawn'},{pos:'SG',name:'Cahmmie'},{pos:'SF',name:'Cal'},{pos:'PF',name:'Tsutsumi'},{pos:'C',name:'Ire'} ],
      second:[ {pos:'PG',name:'Chris'},{pos:'SG',name:'Javon'},{pos:'SF',name:'Cartier'},{pos:'PF',name:'Tax'},{pos:'C',name:'Zion'} ],
      third:[ {pos:'PG',name:'ZPud'},{pos:'SG',name:'Partum'},{pos:'SF',name:'MaybeLaMelo'},{pos:'PF',name:'Combat'},{pos:'C',name:'Pelon'} ],
      defensive:[ {pos:'PG',name:'Combat'},{pos:'SG',name:'Cal'},{pos:'SF',name:'Cartier'},{pos:'PF',name:'Trigg'},{pos:'C',name:'Tax'} ],
    },
  },
  {
    id:8, champion:'Boston Celtics', record:'22-14',
    defeated:'Oklahoma City Thunder', defeatedRecord:'47-13', seriesResult:'2-1 (3 Games)',
    owners:['Tom','Slapclosed','UN90247807','spazfromyukatan','LeBewwy','Pox','Dohziez'],
    toty:'Oklahoma City Thunder', fmvp:'Slapclosed',
    awards:{ MVP:'Cal', OPOTY:'Tsutsumi', DPOY:'Minis', PMOTY:'Kai', ROTY:'Aether',
             CPOTY:'Tsutsumi', MIP:'Partum', '4MOTY':'Love' },
    statLeaders:{ 'Scoring Champion':'Tsutsumi','Steals Leader':'Cam','Assist Leader':'Tax','Player Efficiency Rating':'Aether','Turnover Leader':'PatPat' },
    allRPL:{
      first:[ {pos:'PG',name:'Kai'},{pos:'SG',name:'Tsutsumi'},{pos:'SF',name:'Cal'},{pos:'PF',name:'Cartier'},{pos:'C',name:'Cahmmie'} ],
      second:[ {pos:'PG',name:'Roji'},{pos:'SG',name:'Aether'},{pos:'SF',name:'Tom'},{pos:'PF',name:'Acro'},{pos:'C',name:'Loq'} ],
      third:[ {pos:'PG',name:'Tax'},{pos:'SG',name:'Partum'},{pos:'SF',name:'Chris'},{pos:'PF',name:'Javon'},{pos:'C',name:'Mikey'} ],
      defensive:[ {pos:'PG',name:'Durkio'},{pos:'SG',name:'Minis'},{pos:'SF',name:'Love'},{pos:'PF',name:'Cal'},{pos:'C',name:'Cartier'} ],
    },
  },
  {
    id:9, champion:'Houston Rockets', record:'27-17',
    defeated:'Miami Heat', defeatedRecord:'26-5', seriesResult:'1-0 (1 Game)',
    owners:['Tom','Aether','Durkio','Pekka','Pox','K20'],
    toty:'Miami Heat', fmvp:'Aether',
    awards:{ MVP:'Loq', OPOTY:'Aether', DPOY:'Love', PMOTY:'Tax', ROTY:'Oil',
             CPOTY:'Roji', MIP:'Ire', '4MOTY':'Pox' },
    statLeaders:{ 'Scoring Champion':'Aether','Steals Leader':'Love','Assist Leader':'Tax','Rebounds Leader':'Dohziez','Player Efficiency Rating':'Loq','Turnover Leader':'Javon' },
    allRPL:{
      first:[ {pos:'PG',name:'Kai'},{pos:'SG',name:'Loq'},{pos:'SF',name:'Tsutsumi'},{pos:'PF',name:'Aether'},{pos:'C',name:'Oil'} ],
      second:[ {pos:'PG',name:'Love'},{pos:'SG',name:'Roji'},{pos:'SF',name:'Minis'},{pos:'PF',name:'Shawn'},{pos:'C',name:'Cartier'} ],
      third:[ {pos:'PG',name:'Aimcancel'},{pos:'SG',name:'Chris'},{pos:'SF',name:'Tax'},{pos:'PF',name:'Cal'},{pos:'C',name:'Logs'} ],
      defensive:[ {pos:'PG',name:'Minis'},{pos:'SG',name:'Love'},{pos:'SF',name:'Loq'},{pos:'PF',name:'Tom'},{pos:'C',name:'Cartier'} ],
    },
  },
  {
    id:10, champion:'San Antonio Spurs', record:'11-5',
    defeated:'Philadelphia 76ers', defeatedRecord:'11-4', seriesResult:'2-1 (1 Game)',
    owners:['Tom','bugwars','conzlx','MELO','Dohziez','1v_k','Northside','Pox','ZPud'],
    toty:'Philadelphia 76ers', fmvp:'ZPud',
    awards:{ MVP:'Chris', OPOTY:'Cahmmie', DPOY:'Minis', PMOTY:'Roji', ROTY:'Pop',
             CPOTY:'Tsutsumi', MIP:'Pox', '5MOTY':'Eazy' },
    statLeaders:{ 'Scoring Champion':'Pox','Assist Leader':'Roji','Rebounds Leader':'Shawn','Player Efficiency Rating':'Cahmmie' },
    allRPL:{
      first:[ {pos:'PG',name:'Tom'},{pos:'SG',name:'Cahmmie'},{pos:'SF',name:'Aether'},{pos:'PF',name:'Tsutsumi'},{pos:'C',name:'Chris'} ],
      second:[ {pos:'PG',name:'Shawn'},{pos:'SG',name:'Berry'},{pos:'SF',name:'Logs'},{pos:'PF',name:'Pox'},{pos:'C',name:'Cal'} ],
      third:[ {pos:'PG',name:'Minis'},{pos:'SG',name:'Roji'},{pos:'SF',name:'Tax'},{pos:'PF',name:'Love'},{pos:'C',name:'Cartier'} ],
      defensive:[ {pos:'PG',name:'Minis'},{pos:'SG',name:'Mari'},{pos:'SF',name:'Cahmmie'},{pos:'PF',name:'Love'},{pos:'C',name:'Cartier'} ],
    },
  },
];

module.exports = { DEFAULT_ALLSTAR, DEFAULT_RECORDS, DEFAULT_SEASONS };
